wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.generate, name="generate")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from . import util


def index(request):

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def generate(request,title):

    titleU = title.upper()
    titleC = title.capitalize()
    contentU = util.get_entry(titleU)
    contentC = util.get_entry(titleC)

    if titleU == "CSS" or titleU == "HTML":
        return render(request,f"encyclopedia/{titleU}.html",{
            "content": contentU
        })
    else:
        if contentC == None:
            return render(request, f"encyclopedia/error.html")
        return render(request, f"encyclopedia/{titleU}.html",{
            "content": contentC
        })
        




 

wiki/encyclopedia/templates/encyclopedia/CSS.html
{% extends 'encyclopedia/layout.html' %} {% block title %} CSS {% endblock %}
{%block body %}

<p>{{content}}</p>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/DJANGO.html
{% extends 'encyclopedia/layout.html' %} {% block title %} Django {% endblock %}
{%block body %}

<p>{{content}}</p>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/GIT.html
{% extends 'encyclopedia/layout.html' %} {% block title %} GIT {% endblock %}
{%block body %}

<p>{{content}}</p>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/HTML.html
{% extends 'encyclopedia/layout.html' %} {% block title %} Html {% endblock %}
{%block body %}

<p>{{content}}</p>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/PYTHON.html
{% extends 'encyclopedia/layout.html' %} {% block title %} Python {% endblock %}
{%block body %}

<p>{{content}}</p>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends 'encyclopedia/layout.html' %} {% block body %}

<h1>ERROR 404</h1>

<p>Page was not found</p>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %} {% block title %} Encyclopedia
{%endblock %} {% block body %}
<h1>All Pages</h1>

<ul>
  {% for entry in entries %}
  <li><a href="{{entry}}">{{entry}}</a></li>
  {% endfor %}
</ul>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet" />
  </head>
  <body>
    <div class="row">
      <div class="sidebar col-lg-2 col-md-3">
        <h2>Wiki</h2>
        <form>
          <!-- {% csrf_token %} -->

          <input
            class="search"
            type="text"
            name="q"
            placeholder="Search Encyclopedia"
          />
        </form>
        <div>
          <a href="{% url 'wiki:index' %}">Home</a>
        </div>
        <div>Create New Page</div>
        <div>Random Page</div>
        {% block nav %} {% endblock %}
      </div>
      <div class="main col-lg-10 col-md-9">{% block body %} {% endblock %}</div>
    </div>
  </body>
</html>